export const typeMockConstants = {
    GROUP_PROFILE: "GROUP_PROFILE",
    AVENUES_PROFILE: "AVENUES_PROFILE",
    SERVICES_PROFILE: "SERVICES_PROFILE",
    MAGIC_TOWNS_PROFILE: "MAGIC_TOWNS_PROFILE",
}