const videoRailViewPlayConstants = {
    VIDEORAILVIEWPLAY: "VIDEORAILVIEWPLAY",
    VIDEORAILVIEWPLAY_FETCHING: "VIDEORAILVIEWPLAY_FETCHING",
    VIDEORAILVIEWPLAY_ERROR: "VIDEORAILVIEWPLAY_ERROR",
}

export default videoRailViewPlayConstants;